# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: avatar_data_frames.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'avatar_data_frames.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18\x61vatar_data_frames.proto\x12\x0f\x61\x63hatbot_frames\"\xb1\x01\n\x16\x41nimationAudioRawFrame\x12\n\n\x02id\x18\x01 \x01(\x04\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05\x61udio\x18\x03 \x01(\x0c\x12\x13\n\x0bsample_rate\x18\x04 \x01(\r\x12\x14\n\x0cnum_channels\x18\x05 \x01(\r\x12\x14\n\x0csample_width\x18\x06 \x01(\r\x12\x16\n\x0e\x61nimation_json\x18\x07 \x01(\t\x12\x15\n\ravatar_status\x18\x08 \x01(\t\"T\n\x05\x46rame\x12\x42\n\x0f\x61nimation_audio\x18\x01 \x01(\x0b\x32\'.achatbot_frames.AnimationAudioRawFrameH\x00\x42\x07\n\x05\x66rameb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'avatar_data_frames_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ANIMATIONAUDIORAWFRAME']._serialized_start=46
  _globals['_ANIMATIONAUDIORAWFRAME']._serialized_end=223
  _globals['_FRAME']._serialized_start=225
  _globals['_FRAME']._serialized_end=309
# @@protoc_insertion_point(module_scope)
