[cerebrium.deployment]
name = "fastapi-daily-bot"
python_version = "3.11"
#cuda_version = "12"
include = "[./*, main.py, cerebrium.toml]"
exclude = "[.*]"
shell_commands = []
# need daily-python with daily-core daily-webRTC
docker_base_image_url = "prod.registry/daily:latest"

[cerebrium.hardware]
#gpu = "AMPERE_A10"
#gpu_count = 1
cpu = 2
memory = 8.0
compute = "CPU"
provider = "aws"
region = "us-east-1"

[cerebrium.scaling]
min_replicas = 0
max_replicas = 5
cooldown = 60

[cerebrium.dependancies.pip]
"achatbot[fastapi_daily_bot_server]" = "latest"
