apiVersion: v1
kind: Secret
metadata:
  name: fastapi-daily-chat-bot-secret
  namespace: achatbot
type: Opaque
data:
  # echo -n "***" | base64
  REDIS_PASSWORD: <REDIS_PASSWORD>
  TIDB_PASSWORD: <TIDB_PASSWORD>
  OPENAI_API_KEY: <OPENAI_API_KEY>
  GROQ_API_KEY: <GROQ_API_KEY>
  TOGETHER_API_KEY: <TOGETHER_API_KEY>
  DAILY_API_KEY: <DAILY_API_KEY>
  CARTESIA_API_KEY: <CARTESIA_API_KEY>
  DEEPGRAM_API_KEY: <DEEPGRAM_API_KEY>
  ELEVENLABS_API_KEY: <ELEVENLABS_API_KEY>
  JINA_API_KEY: <JINA_API_KEY>