AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Sam Template

Globals:
  Function:
    Timeout: 30

Resources:
  FastapiDailyChatBotFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: "FastapiDailyChatBotLambda"
      #MemorySize: 128
      CodeUri: runtime/
      Handler: app.handler
      Runtime: python3.11
      Events:
        Api:
          Type: HttpApi
          Properties:
            ApiId: !Ref Api

  Api:
    Type: AWS::Serverless::HttpApi

Outputs:
  ApiUrl:
    Description: URL of your API endpoint
    Value:
      Fn::Sub: 'https://${Api}.execute-api.${AWS::Region}.${AWS::URLSuffix}/'
  FastapiDailyChatBotFunciton:
    Description: "Fastapi Daily Chat Bot Lambda Function ARN"
    Value: !GetAtt FastapiDailyChatBotFunction.Arn
  FastapiDailyChatBotFuncitonIamRole:
    Description: "Implicit IAM Role created for Fastapi Daily Chat Bot Lambda Function"
    Value: !GetAtt FastapiDailyChatBotFunctionRole.Arn