AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Sam Template

Globals:
  Function:
    Timeout: 30

Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: "FastapiDailyChatBotLambda"
      MemorySize: 128
      CodeUri: app
      Handler: src.cmd.http.server.fastapi_daily_bot_serve.handler
      Runtime: python3.11
      Events:
        Api:
          Type: HttpApi
          Properties:
            ApiId: !Ref Api

  Api:
    Type: AWS::Serverless::HttpApi

Outputs:
  ApiUrl:
    Description: URL of your API endpoint
    Value:
      Fn::Sub: 'https://${Api}.execute-api.${AWS::Region}.${AWS::URLSuffix}/'